#!/usr/bin/env python3
"""
Demo script to show SMS-Prompt CLI interface without sending actual messages
"""

print("=" * 60)
print("📱 SMS-Prompt - Send SMS via Twilio")
print("=" * 60)
print()
print("This is a demo of the SMS-Prompt CLI interface.")
print("To actually send messages, configure your .env file with Twilio credentials.")
print()
print("-" * 60)
print()
print("📤 Sending from: +1234567890 (demo)")
print()
print("-" * 60)
print()
print("📞 Enter recipient phone number (e.g., +1234567890): +19998887777")
print()
print("📝 Enter your message (press Enter twice when done):")
print("-" * 60)
print("Hello! This is a test message from SMS-Prompt.")
print()
print("=" * 60)
print("🚀 Sending message...")
print("=" * 60)
print()
print("🔄 Attempt 1 of 3...")
print("📤 Sending to: +19998887777")
print("📤 From: +1234567890")
print("📝 Message: Hello! This is a test message from SMS-Prompt.")
print()
print("✅ Message sent successfully!")
print("  📧 Message SID: SMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
print("  📊 Status: queued")
print("  💰 Price: 0.0079 USD")
print()
print("=" * 60)
print("✅ Message delivered successfully!")
print("=" * 60)
